export enum CatalogAttributeApplyToEnum {
	SIMPLE = "SIMPLE",
	VIRTUAL = "VIRTUAL",
	BUNDLE = "BUNDLE",
	DOWNLOADABLE = "DOWNLOADABLE",
	CONFIGURABLE = "CONFIGURABLE",
	GROUPED = "GROUPED",
	CATEGORY = "CATEGORY",
}