import {String} from "./gql.string";
import {PayflowLinkMode} from "./gql.payflowLinkMode";
export type PayflowLinkToken = {
	mode?: PayflowLinkMode // The mode for the Payflow transaction.
	paypal_url?: String // The PayPal URL used for requesting a Payflow form.
	secure_token?: String // The secure token generated by PayPal.
	secure_token_id?: String // The secure token ID generated by PayPal.
}