export enum ValidatePurchaseOrderErrorType {
	NOT_FOUND = "NOT_FOUND",
	OPERATION_NOT_APPLICABLE = "OPERATION_NOT_APPLICABLE",
	COULD_NOT_SAVE = "COULD_NOT_SAVE",
	NOT_VALID_DATA = "NOT_VALID_DATA",
	UNDEFINED = "UNDEFINED",
}