export enum ValidationRuleEnum {
	DATE_RANGE_MAX = "DATE_RANGE_MAX",
	DATE_RANGE_MIN = "DATE_RANGE_MIN",
	FILE_EXTENSIONS = "FILE_EXTENSIONS",
	INPUT_VALIDATION = "INPUT_VALIDATION",
	MAX_TEXT_LENGTH = "MAX_TEXT_LENGTH",
	MIN_TEXT_LENGTH = "MIN_TEXT_LENGTH",
	MAX_FILE_SIZE = "MAX_FILE_SIZE",
	MAX_IMAGE_HEIGHT = "MAX_IMAGE_HEIGHT",
	MAX_IMAGE_WIDTH = "MAX_IMAGE_WIDTH",
}