import {Boolean} from "./gql.boolean";
import {String} from "./gql.string";
export type BraintreeInput = {
	device_data?: String // Contains a fingerprint provided by Braintree JS SDK and should be sent with sale transaction details to the Braintree payment gateway.
	is_active_payment_token_enabler: Boolean // States whether the payment details (Credit/Debit Card, PayPal Account) entered by a customer should be tokenized for later usage. Required only if Vault is enabled for the relevant Braintree payment integration.
	payment_method_nonce: String // The one-time payment token generated by Braintree payment gateway based on payment details (Card, PayPal). Required field to make sale transaction.
}