import {String} from "./gql.string";
import {Float} from "./gql.float";
export type CreatePaymentOrderOutput = {
	amount?: Float // The amount of the payment order
	currency_code?: String // The currency of the payment order
	id?: String // PayPal order ID
	mp_order_id?: String // The order ID generated by Payment Services
	status?: String // The status of the payment order
}