export enum ReCaptchaFormEnum {
	PLACE_ORDER = "PLACE_ORDER",
	CONTACT = "CONTACT",
	CUSTOMER_LOGIN = "CUSTOMER_LOGIN",
	CUSTOMER_FORGOT_PASSWORD = "CUSTOMER_FORGOT_PASSWORD",
	CUSTOMER_CREATE = "CUSTOMER_CREATE",
	CUSTOMER_EDIT = "CUSTOMER_EDIT",
	NEWSLETTER = "NEWSLETTER",
	PRODUCT_REVIEW = "PRODUCT_REVIEW",
	SENDFRIEND = "SENDFRIEND",
	BRAINTREE = "BRAINTREE",
	RESEND_CONFIRMATION_EMAIL = "RESEND_CONFIRMATION_EMAIL",
}