import {Int} from "./gql.int";
import {String} from "./gql.string";
export type CreatePayflowProTokenOutput = {
	response_message: String // The RESPMSG returned by PayPal. If the result is 0, then response_message is Approved.
	result: Int // A non-zero value if any errors occurred.
	result_code: Int // The RESULT returned by PayPal. A value of 0 indicates the transaction was approved.
	secure_token: String // A secure token generated by PayPal.
	secure_token_id: String // A secure token ID generated by PayPal.
}