import {PaymentSourceDetails} from "./gql.paymentSourceDetails";
import {String} from "./gql.string";
export type PaymentOrderOutput = {
	id?: String // PayPal order ID
	mp_order_id?: String // The order ID generated by Payment Services
	payment_source_details?: PaymentSourceDetails // Details about the card used on the order
	status?: String // The status of the payment order
}