export enum CartUserInputErrorType {
	PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
	NOT_SALABLE = "NOT_SALABLE",
	INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
	COULD_NOT_FIND_CART_ITEM = "COULD_NOT_FIND_CART_ITEM",
	REQUIRED_PARAMETER_MISSING = "REQUIRED_PARAMETER_MISSING",
	INVALID_PARAMETER_VALUE = "INVALID_PARAMETER_VALUE",
	UNDEFINED = "UNDEFINED",
	PERMISSION_DENIED = "PERMISSION_DENIED",
}