export enum GiftRegistryDynamicAttributeGroup {
	EVENT_INFORMATION = "EVENT_INFORMATION",
	PRIVACY_SETTINGS = "PRIVACY_SETTINGS",
	REGISTRANT = "REGISTRANT",
	GENERAL_INFORMATION = "GENERAL_INFORMATION",
	DETAILED_INFORMATION = "DETAILED_INFORMATION",
	SHIPPING_ADDRESS = "SHIPPING_ADDRESS",
}