export enum PurchaseOrderStatus {
	PENDING = "PENDING",
	APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
	APPROVED = "APPROVED",
	ORDER_IN_PROGRESS = "ORDER_IN_PROGRESS",
	ORDER_PLACED = "ORDER_PLACED",
	ORDER_FAILED = "ORDER_FAILED",
	REJECTED = "REJECTED",
	CANCELED = "CANCELED",
	APPROVED_PENDING_PAYMENT = "APPROVED_PENDING_PAYMENT",
}